---
title: "Summary of Xiaoyan Zhang's Master's Thesis"
author: "Michael Kovaliov"
date: "22-2-2021"
output: pdf_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The idea of this thesis:

In the first chapter, basic ideas regarding volatility modeling are presented.
In the second chapter, we introduce the concept of fractional Brownian motion(fBm).
In the third chapter we talk about an actual model of rough volatility, which relies heavily on fBm.
In the fourth chapter we look at an extension for derivative pricing.

## Summary of chapter 1

In chapter 1 there were 3 main parts

The first talked about some generic facts about volatility and modeling assets, both theoretical and practical aspects.
One practical aspect which is sometimes neglected in theory is leverage - the more debt a firm has w.r.t. its earning, its volatility is going to be higher.
In practice volatility also clusters and has a long memory.

The next part talked about how to actually find the volatility of a stock price.
One method was using the derived from the Black & Scholes framework.
This is inconsistent with practice because in practice the volatility is not constant.Another idea was time-dependent volatility model, which is still built upon B&S.
It considers the dynamic of a stock price with time-dependent(yet deterministic) volatility:

$\displaystyle \frac{dS(t)}{S(t)} = \mu dt + \sigma(t)dW(t)$

Merton(1973) proposed the pricing formula using dependent volatility.
If we use the annualized variance:

$\displaystyle \sigma_a=\sqrt{\frac{1}{T-t}\int_t^T\sigma^2(\tau)d\tau}$

And view $\sigma_a$ as a constant dependent upon $t$ and $T$, you can plug it into B&S and receive a formula which when solved gives you time-dependent volatility.
Local volatility and mixture models were also mentioned in this part.

The last part talks about the following model: $\displaystyle \frac{dS(t)}{S(t)} = \mu_t dt + \sigma(t)dW(t)_1$

The stock price is driven by the wiener process $W_1$ and $\mu_t$ is the drift term.
However the volatility $\sigma(t)$ now is also stochastic.
Typically the volatility will be governed by a SDE which is driven by another Wiener process $W_2$ that is correlated with $W_1$.
The author then described popular SDEs that are used with this model.
For example:

-   Scott(1987)

$\displaystyle dS(t) = \mu_1S(t)dt + \sigma(t)S(t)^{\kappa}dW_1(t),$

$\displaystyle d\sigma(t) = \mu_2\sigma(t)dt+\delta\sigma^{\beta}(t)dW_2(t)$

and that is the end of chapter 1.

## Summary of chapter 2 - fractional Brownian motion.

Here it gets interesting.
The idea is to replace the usual Brownian motion with a fractional Brownian motion(fBm) in a SDE model.
To do that we need to define an integral on fBm, and figure out a lot of basic properties.
Lets do it!

A short preliminary for myself:

### (Preliminary) Gaussian process

***Definition Gaussian random variable** An* $\mathbb{R}^d$-valued random variable $\xi=(\xi_1,...,\xi_d)$ is called a Gaussian random variable if, for any $y\in\mathbb{R}^d$, $<y,\xi>$ is a real-valued Gaussian random variable.

If $\xi$ is an $\mathbb{R}^d$-valued Gaussian random variable, we define, for $j=1,...,d$,$m_j=\mathbb{E}[\xi_j]$.
Then $m=(m_1,...,m_d)$ is called the mean of $\xi$.
The matrix $\sum=(\sum_{jk})$ defined by

$$
\sum_{jk} = \mathbb{E}[(\xi_j-m_j)(\xi_k-m_k)]
$$

is called the covariance matrix of $\xi$.

A real-values process $X=(X_t:t\ge0)$ is called a **Gaussian process** if, for any $n\ge1$ and $0\le t_1 \le... \le t_n < \infty$, $(X_{t_1},...,X_{t_n})$ is a Gaussian random variable.

If $X$ is a Gaussian process, we may define:

$$
m(t) = \mathbb{E}[X_t], \quad t\ge0
$$

$$
\sum(s,t)=\mathbb{E}[(X_s-m(s))(X_t-m(t))],\quad s,t\ge0
$$

$m(t)$ is the mean function, $\sum(s,t)$ is called the covariance kernel.
If $\forall t:m(t)=0$ then $X$ is called a centered Gaussian process.
The Gaussian process is characterized by mean and covariance kernel.

**Proposition:** A standard 1-dimensional Brownian motion is a centered Gaussian process with covariance kernel $\sum(s,t)=s \wedge t = min(s,t)$

So a Brownian motion is actually a centered Gaussian process, but not the only one.
We will now see other forms of Gaussian processes.

**Definition semimartingale** a real values process $X$ on the filtered probability space $(\Omega, \mathcal{F}, (\mathcal{F_t})_{t\ge0},P)$ is called asemimartingale if it can be decomposed as$$X_t = M_t + A_t$$

where $M$is a local martingale and A is s Càdlàg adapted process(everywhere right continuous, has left limits everywhere. may contain jumps) of locally bounded variation.

Semimartingale is a kind of merge between a martingale-like process and a non-martingale process.

### Elementary properties of fBm

***Definition: fraction Brownian motion (fBm)** A centered Gaussian process* $B^H=\{B_t^H,t\in\mathbb{R}\}$ is called a two-sided fractional Brownian motion (fBm) with Hurst parameter $H\in(0,1)$ if it has covariance function:

$\displaystyle R_H(t,s)=E[B_t^HB_s^H] = \frac{1}{2}(s^{2H}+t^{2H}-|t-s|^{2H})$ $s,t\in\mathbb{R}$

As we have previously seen, this fact (centered+covariance) uniquely determines the distribution.

**Definition: homogeneous function** A *homogeneous function* $f$ of variables $x$ and $y$ is a real-values function that satisfies

$$
f(tx,ty)=t^kf(x,y)
$$

for some constant $k$ and all real numbers $t$.
$k$ is also called *the degree of homogeneity.*

**Definition: self similar** A stochastic process $(X_t)_{t\ge0}$ is called *self-similar* if there exists a real number $H>0$ such that for any $c>0$ the processes $(X_{ct})_{t\ge0}$ and $(c^HX_t)_{t\ge0}$ have the same finite dimensional distributions.

Fact - fBm has homogeneous covariance function, and fBm is self similar.

Fact - $\mathbb{E}[|B_t^H - B_s^H|^2]=|t-s|^{2H}\quad s,t\in\mathbb{R}$ , which implies stationary increments

**Theorem: Kolmogorov-Chentsov Continuity Theorem.** Assume that for a stochastic process $\{X_t, t\ge0\}$ such that for $s,t,\in[0,T]$ and $T\ge0$,

$$
\mathbb{E}[|X_t - X_s|^p]\le|t-s|^{1+\beta},
$$

with positive constants $p,\beta,D$.
Then there exists a continuous modification $\hat X$ of $X$, i.e.

1.  $\hat X$ has **continuous paths**.
2.  $P(X_t=\hat X_t)=1$ for $t\in[0,T]$

Furthermore, the process $\hat X$ is $\kappa$-Holder continuous, i.e for any $0<\kappa<\frac{\beta}{p}$

$$
\sup_{0\le s<t\le T} \frac{|\hat X_t - \hat X_s|}{(t-s)^\kappa}<\infty
$$

This Theorem can be applied for fBm.
This is useful because in the near future we may just look at fBm as continuous, implicitly choosing always the continuous modification of the process.

Fact - when the Hurst parameter $H=\frac{1}{2}$ then we receive the standard Brownian motion: $B_t^{\frac{1}{2}}$, with covariance $\mathbb{E}[B_t^{\frac{1}{2}}B_s^{\frac{1}{2}}] = min(|s|,|t|)$ .

Fact: If we define $R_H(n)$ where $s+h\le t, \quad t-s=nh$ as :

$$
R_H(n)=\mathbb{E}[(B_{t+h}-B_t)(B_{s+h}-B_s)]
$$

Then:

1.  When $H\in(0,\frac{1}{2})$, $R_H(n)<0$ then the increments are negatively correlated and the process presents counter persistence. Furthermore: $\sum_{n=1}^\infty |R_H(n)|<\infty$
2.  When $H\in(\frac{1}{2},1), R_H(n)>0$ then the increments are positively correlated and the process is persistent. Furthermore: $\sum_{n=1}^\infty R_H(n)=\infty$

Fact: when the Hurst parameter $H\in(0,\frac{1}{2})\cup(\frac{1}{2}, 1)$, **the increments of the fBm on disjoint intervals are not independent**, and also **the process is not a semimartingale.**

### Mandelbrot-Van Ness representation of fBm

We create the two-sided Wiener process:

$$
W_t=\begin{cases}
W_t^1,    \quad \; t\ge0\\
W_{-t}^2, \quad t<0
\end{cases}
$$

$W^1, W^2$ are independent on $[0,\infty)$

Given a step function $$g(x)=\sum_{k=1}^{n}a_k\textbf{1}_{[s_k,t_k]}(x),$$

define the integral:

$$
I(g)=\int_Rg(x)dW(x)=\sum_{k=1}^na_k(W_{t_k}-W_{s_k})
$$

Few properties: Can be extended from step function to functions in $L^2(\mathbb{R})$.
This integral is also linear, its mean is zero, and it keeps isometry: $\mathbb{E}[I(f)I(g)]=\int_{\mathbb{R}}f(x)g(x)dx.$ Also, for $h_1,...,h_n\in L^2(\mathbb{R})$ the random variables $I(h_1),...,I(h_n)$ are jointly Gaussian distributed.

Now suppose the the fBm $B_t^H$ can be represented in the following form:

$$
B_t^H=I(k_H(t)) = \int_{\mathbb{R}}k_H(t,x)dW_x
$$

Where $k_H(t)$ is a deterministic kernel.
Because the mean of the integral is 0, if you show that the same covariance as the fBm is achieved you have proved the process is fBm.

**Theorem:** the fBm above is achieved with

$$
B_t^H=\frac{1}{C^{(1)}(H)}\int_{\mathbb{R}}k_H(t,u)dW_u
$$ where: $$
\frac{1}{C^{(1)}(H)} = (\int_{\mathbb{R}^+} ((1+s)^\kappa-s^\kappa)^2ds+\frac{1}{2H})^\frac{1}{2}
$$ and $$k_H(t,u):=(t-u)^\kappa_+-(-u)^\kappa_+$$ with $\kappa = H-\frac{1}{2}$.

### Fractional integrals and derivatives

Let $a,b\in\mathbb{R},a<b,\alpha>0$ and $f\in L^1(a,b)$.
The Riemann-Liouville left and right-sided integrals are defined on $(a,b)$ of order $\alpha$ by

$$
(I_{a^+}^\alpha f)(x):=\frac{1}{\Gamma(\alpha)}\int_a^xf(y)(x-y)^{\alpha-1}dy
$$\
and$$
(I_{b^-}^\alpha f)(x):=\frac{1}{\Gamma(\alpha)}\int_x^b f(y)(y-x)^{\alpha-1}dy
$$

respectively.
If a function $f$ inside the proper function space is an integral, the left and right sided derivatives are defined by:

$$
(D_{a^+}^\alpha f)(x)=\frac{1}{\Gamma(1-\alpha)} \left(\frac{f(x)}{(x-a)^\alpha}+\alpha\int_a^x\frac{f(x)-f(y)}{(x-y)^{\alpha+1}}dy\right)
$$

and

$$
(D_{b^-}^\alpha f)(x)=\frac{1}{\Gamma(1-\alpha)} \left( \frac{f(x)}{(b-x)^\alpha}+\alpha \int_x ^b\frac{f(x)-f(y)}{(x-y)^{\alpha+1}}dy \right)
$$

### Representation of fBm on an interval

Fix a time interval $[0,T]$ and denote the set of step functions on $[0,T]$ by $\bf S$.
Let ${B_t^H, t\in[0,T]}$ be the fBm with Hurst parameter $H\in(0,1)$, and let $\mathcal{H}$ be the closure of $\bf S$ with respect to the scalar product:

$$
\displaystyle < \textbf{1}_{[0,t]}, \textbf{1}_{[0,s]}>=R_H(t,s)
$$

**This is the big thing about the fractional Brownian motion.** This scalar product, and the integrals and derivatives that were previously defined lead to a long proof to an important identity which states that you can get from Brownian motion to fBm using certain kernel functions.
The identity as described in the paper:

$$
\int_0^T\gamma(t)dB_t=\int_0^T(K^*_H\gamma)(t)dW_t
$$

This looks scary but this isn't really:

$\gamma$ is just a member inside $\mathcal{H}$

$B_t$ here denotes **fractional** Brownian motion

$W_t$ denotes Brownian motion / Wiener process

$K_H$ is an appropriate kernel function, from this function we derive the operator $K^*_H$ which is defined like this: $(K^*_H\gamma)(s)=\int_s^T\gamma(t) \left( \frac{\partial K_H}{\partial t}\right)(t,s)dt$

### Simulation of fBm

The author goes into detail on how to generate a time series that represents a fBm.

## Summary of chapter 3 - Rough fractional stochastic volatility.

The logarithm of realized variance behaves essentially as fractional Brownian motion with Hurst parameter $H=0.1$.
This leads to the Rough Fractional Stochastic Volatility (RFSV) model, which is based on the Fractional Stochastic Volatility model.

### Fractional volatility

The FSV model:

$$
\frac{dS_t}{S_t}=\sigma_tdZ_t
$$

$$
dlog(\sigma_t)=\nu dW_t^H+\alpha(m-log(\sigma_t))dt
$$

where $Z_t$ is standard Brownian motion and $W_t^H$ is fBm represented with:

$$
\displaystyle W_t^H=\int_0^t\frac{(t-s)^{H-\frac{1}{2}}}{\Gamma(H+\frac{1}{2})}dW_s,\quad \frac{1}{2}\le H<1
$$

and

$$
\mathbb{E}[dW_tdZ_t]=\rho dt
$$

The fBm has long memory, so the choice of $H\ge\frac{1}{2}$ captures that.

### Scaling property and normality

It is important to remember how observed volatility looks:

$$
\displaystyle
m(q,\Delta)=\frac{1}{N}\sum_{k=1}^N |\log(\sigma_{k\Delta})-\log(\sigma_{(k-1)\Delta})|^q
$$

where $\{ \sigma_{k\Delta} \} _{k}$ is a volatility process on $[0,T],k\in \{ 0,[T/\Delta] \}, N=[T/\Delta]$ and $q \ge0$.

$m(q,\Delta)$ can be viewed as the empirical counterpart of the following size:

$$
m(q,\Delta)"="\mathbb{E}[|\log(\sigma_\Delta)-\log(\sigma_0)|^q]
$$

Scaling property:

$$
\mathbb{E}[|\log(\sigma_\Delta-\log(\sigma_0)|^q] = C_q\Delta^{\zeta_q}
$$

You can plug many different q values to try to estimate $\zeta_q$ which will give you $H$.
Testing against realized volatility of famous datasets we get results around $H=0.1$.
Because the $H \ll\frac{1}{2}$ , the volatility is rough(the counter - persistence property that fBm has in that situation is the roughness)

### The Ornstein-Uhlenbeck process

The RFSV model uses the OU process, so it will be useful to know more about it.

Given the Langevin ODE which describes particle movement in a fluid:

$$
\frac{dv(t)}{dt}=-\frac{f}{m}v(t)+\frac{F(t)}{m}
$$

where $m$ is particle mass, $f>0$ is the friction coefficient and $F(t)$ is the force on the particle by the impact of molecules in the fluid.
The OU process may be defined as the strong solution to the ODE with Brownian noise, the according SDE will look like this(with parameter $\lambda$ and $\sigma$):

$$
\displaystyle X_t=\xi-\lambda\int_0^tX_sds+\sigma B_t,t\ge0,
$$

With random initial condition $\xi=\sigma\int_{-\infty}^0e^{\lambda u}dB_t$, the solution is given by

$$
Y_t=\sigma\int_{-\infty}^{t}e^{-\lambda (t-u)}dB_u,\quad t\ge0$$

This solution is stationary.

The idea is to use this OU SDE and solution and instead of using regular Brownian motion we will plug in the fBm.
So the author proves that When replacing the Brownian motion in $Y_t$ with $dB_t^H$ is will also be strictly stationary.

The newly crafted solution will look like: $$Y_t^{H,\xi}:=e^{-\lambda t}(\xi+\sigma\int_0^te^{\lambda u}dB_u^H),\quad t\ge0$$

### From the scaling property to the RFVS model

We have observed two properties of realized log volatility:

1.  The increment of log volatility is Gaussian distributed
2.  Scaling property seems to be universal (dumbly summarizing: as we look more closely at fBm, we find more fBm, and not something more similar to something else, e.g. parabola is similar to a line when looking closely.)

It might be a natural construction to do the following:

$$\log(\sigma_{t+\Delta})-\log(\sigma_t)=\nu(B_{t+\Delta}^H-B_t^H)$$

where $\sigma_t$ is our volatility and $B_t^H$ is our fBm with Hurst parameter $H$

We may rewrite the equation as:

$$
\sigma_t=\sigma \exp(\nu B_t^H)
$$

where $\sigma$ is a positive constant.

The problem is, that if we define our volatility like this, **it is not stationary**, this is because the fBm is not stationary.

The author suggests the fractional Ornstein-Uhlenbeck mode: We use the stationary solution to the SDE:

$$
dX_t=\nu dB_t^H-\alpha(X_t-m)dt
$$

where $m\in\mathbb{Z},\alpha,\nu$ are positive constants.
The solution to the SDE is:

$$
X_t=\nu\int_{-\infty}^te^{-\alpha(t-s)}dB_t^H+m
$$

That is, our RFSV finally gives the volatility:

$$
\Large \sigma_t=\exp{ \{X_t\} },\quad t\in[0,T]
$$ Some facts:

1.  Model is intended for $H<\frac{1}{2}$
2.  For small $\alpha$, the rate of reversion is small, so we have a model more similar to the non-stationary one.
3.  Given $[0,T]$, when $\alpha\ll \frac{1}{T}$ , the log volatility behaves locally as a fBm.

For my sanity, here is the full RFSV model:

$$
dS_t=\mu_tdt+\sigma_tdB_t
$$

$$
\sigma_t=\exp \{ X_t\},t\in[0,T]
$$

$$
dX_t=\nu W_t^H-\alpha(X_t-m)dt
$$

## Summary of chapter 4 - option pricing

Now that we have this model, we want to extend it for option pricing.

In this section we rely on Bergomi model, we extend it to rough Bergomi, that is - we use the facts we learned about rough volatility to extend the rBergomi model, and then we change it's measure to risk neutral.
I assume this process makes it much easier for option pricing, but I need to look it up.

### The rBergomi model: the construction

We start with the stock model:

$$
\frac{dS_t}{S_t} = \mu_tdt + \sqrt{v_t}dB_t
$$

where the volatility process is $\sqrt{v_t}$ is driven by fBm.

Given the **instantaneous variance** process $v_t$ ,the **integrated variance** is the quadratic variation of $\log(S_t)$ , and is given by: $\int_t^Tv_sds$

Realized variance is a usual estimation of integrated variance, so this is how we can connect the real life data with our model.

The **forward variance curve** is given by:

$$
\phi_t(s)=\mathbb{E}[v_s|\mathcal{F}_t], \quad s\ge t
$$

We can rewrite the model like this:

$$
\frac{dS_t}{S_t}=\sqrt{\phi_t(t)}dZ_t,
$$

$$
d\phi_t(s)=\alpha \rho(t,s,\phi_t)dW_t
$$

Where $Z_t,W_t$ are two Brownian motions that are connected.

**Side note:** The author mentioned that Bergomi also showed a small noise expansion for the smile:

$$
\sigma_{BS}(k,T)=\sigma_T^* + \alpha\sqrt{\frac{V}{T}}\frac{1}{2V^2}F^{x\phi}k+O(\alpha^2)
$$

Where

-   log-strike $k=log(K/S_t)$

-   $V=\int_0^T\phi_0(u)du$ is the total variance to expiration $T$

-   $\phi_T^*$ is ATM volatility.

-   auto-covariance functional $$F^{x\phi}=\int_0^Tdt \int_t^Tds \frac{\mathbb{E}[dx_t d\phi_t(s)]}{dt}$$

    -   where $x_t=\log(\frac{S_t}{S_0})$

**This is useful for when we want to derive the BS volatility from the actual model**.

Now, after we have a vague idea of what is the forward variance, we can use "n-factor Bergomi model" to yield the following equality:

$$
\phi_t(s)=\phi_0(s)\mathcal{E}\left(\sum_{i=1}^n \delta_i\int_0^t e^{-\zeta_i(s-u)}dW_u^{(i)} \right)
$$

Where:

-   The stochastic exponential, $\mathcal{E}$ is : $\mathcal{E}(X)_t = \exp(X_t-X_0-\frac{1}{2}[X]_t)$

    -   Where $[X]_t$ denotes the quadratic variation of $X_t$.

**Interesting property: when** $X_t$ **is a local martingale, so is** $\mathcal{E}(X_t)$**, while** $\exp(X_t)$ **usually isn't.**

The author states that the n-factor Bergomi representation for the forward variance curve is determined by n OU-processes, when $n=1$ the model can be written as:

$$
\phi_t(s)=\phi_0(s)\exp(\delta e^{-\zeta(s-t)}Y_t - \frac{1}{2}\delta ^ 2 e ^ {-2\zeta (s-t)}\mathbb{E}[Y_t^2])
$$

where $Y_t$ is a scalar OU-process.

**We got a result which is relatively hard to calculate. If we will restructure the model a little, we may get results that are consistent with experiments and more simplified.**

Attempting to do so, we may look at the ATM volatility skew:

$$
\gamma(\tau):= |\frac{\partial}{\partial k} \sigma_{BS}(k,\tau)|_{k=0}
$$

For the Bergomi model it has the following behavior:

$$
\gamma(\tau)\sim\sum_i \frac{\delta_i}{\zeta_i \tau } \{1-\frac{1-e^{-\zeta_i \tau}}{\zeta_i \tau}\}
$$

where $\tau=T-t$, time to expiration.

It is **empirically observed** that the term structure of volatility skew behaves essentially as: $\gamma(\tau) \sim \tau^{-\beta}$ for some $\beta$.

**So we change the exponential kernel to the following model:**

$$
\phi_t(u)=\phi_0(u)\mathcal{E}\left(\delta\int_0^t \frac{dW_s}{(u-s)^\kappa} \right)
$$

and we still have that $\phi_t(u)$ is a local martingale.

Fixing a constant initial value $\phi_0(u) \equiv\sigma_0$, and taking the square root of the forward variance, the instantaneous stochastic volatility process is:

$$
\sigma_t=\sqrt{\phi_t(t)} = \sigma_0 \sqrt{\mathcal{E}\left(\delta \int_0^t \frac{dW_s}{(t-s)^\kappa} \right)} = \sigma_0\exp\{\frac{\delta}{2}N_t - \frac{\delta^2}{4}\mathbb{E}[N_t^2]\} = \sigma_0 \sqrt{\mathcal{E}_W(\delta N_t)}
$$

where $N_t=\int_0^t \frac{dW_s}{(t-s)^\kappa}$ is a Volterra fBm with Hurst parameter $H=\frac{1}{2} - \kappa$, and is also holder continuous of order $H-\epsilon$ .

The wick exponential is given by:

$$
\mathcal{E}_W(\Lambda)= \exp \left (\Lambda-\frac{1}{2}\mathbb{E}[|\Lambda|]^2 \right)
$$

If we revisit the previous equation regarding the volatility representation, we get a very very similar model to the RFSV from the previous chapter.
This is the rBergomi model, and the author suggests we may regard this model as an extension to the usual Bergomi model.
It is useful to express the model precisely like this and not from the previous chapter so we may perform the change of measure easier, which is present in the next chapter.

### Change of measure

If we recall the scaling property:

$$
\log \sigma_t - \log \sigma_s = \zeta(W_t^H-W_s^H), 0<s<t<\infty
$$

We may also recall he Mandelbrot-Van Ness representation of fBm:

$$
W_t^H=\gamma_H \{ \int_{-\infty}^t \frac{dW_s^{\mathbb{P}}}{(t-s)^\kappa}\ - \int_{-\infty}^0\frac{dW_s^{\mathbb{P}}}{(-s)^\kappa}\}
$$

where

-   $\kappa=\frac{1}{2} -H$

-   The parameter: $\gamma_H=\sqrt{(2H\Gamma(3/2-H))/ (\Gamma(H+1/2)\Gamma(2-2H))}$ is determined from the auto-covariance of fBm.

So if we now define:

$$
C_t(u):=\int_t^u\frac{1}{(u-s)^\kappa}dW_s^\mathbb{P}
$$

And also:

$$
N_t(u):=\int_{-\infty}^t[\frac{1}{(u-s)^{\kappa}} - \frac{1}{(t-s)^\kappa}]dW_s^{\mathbb{P}}
$$

We can plug both the Mandelbrot-Van Ness, and the 2 definitions to the scaling property equation to get:

$$
\log v_u - \log v_t = 2\zeta \gamma_H\{C_t(u) + N_t(u)\}
$$

Few notes:

-   $N_t(u)$ is $\mathcal{F}_t$ - measurable

-   $C_t(u)$ is independent of $\mathcal{F}_t$, and is a centered Gaussian process with variance ${(u-t)^{2H}}/(2H)$

We will define $Z_t^{\mathbb{P}}$ which will help us swap measures from the **physical measure** $\mathbb{P}$ to the **risk neutral measure** $\mathbb{Q}$, but more on that later.

$$Z_t^{\mathbb{P}}:=\sqrt{2H}\int_t^u \frac{dW_s^{\mathbb{P}}}{(u-s)^\kappa}$$

Then we write may write $2\zeta \gamma_H C_t(u) = \delta Z_t^{\mathbb{P}}(u)$ where $\delta = 2\zeta\gamma_H / \sqrt{2H}$.
The forecast of the instantaneous volatility at time $u$ given information up to time $t$ is given:

$$\mathbb{E}^{\mathbb{P}}[v_u|\mathcal{F}_t] = v_t \exp \{2\zeta \gamma_H C_t(u) + \frac{1}{2}\delta ^ 2 \mathbb{E}[|Z_t^\mathbb{P(u)}|^2] \}$$ Using Wick's exponential, it follows immediately that:

$$
v_u =v_t\exp \{\delta Z_t^{\mathbb{P}}(u) + 2\zeta \gamma_H N_t(u) \} = \mathbb{E}^{\mathbb{P}}[v_u|\mathcal{F}_t] \mathcal{E}_W(\delta Z_t^{\mathbb{P}}), \quad u > t
$$

We see that $\{ v_t\}_t$ is not Markovian because $N_t(u)$ depends on the full history of $W_t^{\mathbb{P}}$ up to time $t$ .

Also, the conditional distribution of $v_u$ depends on $\mathcal{F}_t$ only through $\mathbb{E}^{\mathbb{P}}[v_u|\mathcal{F}_t]$.

Finally, the model will look like this:

```{=latex}
\begin{equation}
\begin{split}
\frac{dS_u}{S_u} & = \mu_udu+\sqrt{v_u}dB_u^{\mathbb{P}} \\
v_u & = v_t \exp \{ \delta Z_t^{\mathbb{P}} (u) + 2 \zeta \gamma_H N_t(u)\}
\end{split}
\end{equation}
```
Where $B_u^{\mathbb{P}}, W_u^{\mathbb{P}}$ are two standard Brownian motion with constant correlation $\rho$.

We are now able to change measures easier, to the **risk neutral measure** $\mathbb{Q}$.
The risk neutral measure is a probability measure that helps quantify the overall market's risk aversness to a particular asset.
People are naturally risk avers, and even though two stocks might have the same expectation, people would tend to want the one with the lower volatility.
By contrast, the **physical measure**, $\mathbb{Q}$, which is the one used in all of this summary until now, we didn't care about volatility for stock pricing and a stock with expectation of 5\$ would equal 5\$ with 0 volatility or a very high volatility.

As it turns out, if we use the physical measure and we assume that the market is **arbitrage free** ("no free meals"), then we can be certain that the risk neutral measure exists as well.
Also, it is possible to transform a stock price from the risk neutral to the physical measure, and these measures are equivalent.
That is:

Probability $\mathbb{Q}$ is equivalent to the physical probability measure $\mathbb{P}$ in the sense that for all events $A\in\mathcal{F}, \mathbb{P}\sim\mathbb{Q}$, i.e. $\forall A\in \mathcal{F}$:

$$
\mathbb{P}(A)=0 \iff \mathbb{Q}(A)=0
$$

To transform from one measure to another, we may **change measures**, and we want the stock price $S_t$ to be a martingale still after the change of measures.
To achieve that we can use the Girsanov change of measure: $$dB_u^{\mathbb{Q}}=dB_u^{\mathbb{P}} + \frac{\mu_u}{\sqrt{v_u}}du, \quad t\le u\le T$$

This gives:

$$
\frac{dS_u}{S_u} = \sqrt{v_u} dB_u^{\mathbb{Q}}, \quad t \le u \le T
$$

Now $S_u$ is a martingale w.r.t $\mathbb{Q}$ on $u \in [t,T].$ Because $W^{\mathbb{P}}$, $B^\mathbb{P}$ are correlated, there exists $B^{*\mathbb{P}}$ independent from $B^{\mathbb{P}}$ s.t.

$$
W^{\mathbb{P}} = \rho B^\mathbb{P} + \rho^* B^{*\mathbb{P}}, \quad \rho^2 + \rho ^ {*2} = 1
$$

A **general change of measure** $dB^{*\mathbb{P}}$ is the given by: $$dB^{* \mathbb{Q}} = dB^{*\mathbb{P}} + \eta_u du$$

where $\eta_u = \eta(u,\omega), u\in[t,T]$ is a suitable adapted process, and is called **the market price of volatility risk**.
All in all we get:

$$
dW_u^\mathbb{P} = dW_u ^ \mathbb{Q} - \{ \frac{\rho \mu_u}{\sqrt{v_u}} + \rho^* \eta_u \} du
$$

We can write this more compactly:

$$
dW_u^\mathbb{P} = dW_u ^ \mathbb{Q} +\lambda_sds
$$

Plugging in back to the expression of $v_u$ we can see that $v_u$ is no longer lognormal distributed:

\begin{equation}
\begin{split}
 v_u & = \mathbb{E}^\mathbb{P}[v_u | \mathcal{F}_t] \mathcal{E}(\delta Z_t^\mathbb{P}(u)) \\
 & = \mathbb{E}^\mathbb{P}[v_u | \mathcal{F}_t] \exp \{ \delta \sqrt{2H} \times \int_t^u \frac{1}{(u-t)^\kappa}dW_s^\mathbb{P} - \frac{\delta^2}{2} (u-t)^{2H}\} \\
 & = \mathbb{E}^\mathbb{P}[v_u | \mathcal{F}_t] \mathcal{E}(\delta Z_t^\mathbb{Q}(u)) \times \exp{\delta \sqrt{2H} \int _t ^ u \frac{\lambda_s}{(u-s)^\kappa}ds}
\end{split}
\end{equation}

The rBergomi model

Well, after all of this introduction, we will now introduce the final model.

Consider the change of measure:\
$$dW_s^\mathbb{P} = dW_s^\mathbb{Q} + \lambda_s ds $$

For simplicity, $\lambda_t=\lambda(t)$ assumed to be deterministic in $t$.
So we will have:

\begin{equation}
\begin{split}
v_u & = \mathbb{E}^\mathbb{P}[v_u | \mathcal{F}_t] \mathcal{E}(\delta Z_t ^ \mathbb{Q}(u)) \times \exp \{\delta \sqrt{2H} \int_t^u \frac{\lambda(s)}{(u-s)^\kappa} ds \} \\ & =\phi_t(u) \mathcal{E}(\delta Z_t^\mathbb{Q}(u))
\end{split}
\end{equation}

(I assumed they have a typo in the original document)
where $\phi_t(u)=\mathbb{E^Q}[v_u|\mathcal{F}_t]$.
Hence:

$$
\phi_t(u)=\mathbb{E^P}[v_u|\mathcal{F}_t] \exp \{\delta \sqrt{2H} \int _u ^ t \frac{\lambda (s)}{(u-s)^\kappa} ds\}
$$

Since the risk neutral conditional probability is dependent on the full history of the physical Brownian motion, the model is a non-Markovian generalization of the original suggested model for the forward variance.

-   From the way we constructed the mode, it is expected that the ATM implied volatility skew generated from it would be more realistic.

-   The forward variance $\phi_t(u)$ given at the current time $t$ is independent of $t$, and only depends on the parameters $H,\delta,\rho$.

### Simulation of the rBergomi model

The author suggests an algorithm to simulate the rBergomi model, and provides some R code at the end.
